// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using School.API.Data;

namespace School.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220112001434_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("School.API.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Data_Fim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data_Inicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data_Nasc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Matricula")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Data_Inicio = new DateTime(2022, 1, 11, 21, 14, 33, 912, DateTimeKind.Local).AddTicks(9987),
                            Data_Nasc = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 1,
                            Nome = "Marta",
                            Sobrenome = "Kent",
                            Telefone = "33225555"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Data_Inicio = new DateTime(2022, 1, 11, 21, 14, 33, 913, DateTimeKind.Local).AddTicks(2615),
                            Data_Nasc = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 2,
                            Nome = "Paula",
                            Sobrenome = "Isabela",
                            Telefone = "3354288"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Data_Inicio = new DateTime(2022, 1, 11, 21, 14, 33, 913, DateTimeKind.Local).AddTicks(2686),
                            Data_Nasc = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 3,
                            Nome = "Laura",
                            Sobrenome = "Antonia",
                            Telefone = "55668899"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Data_Inicio = new DateTime(2022, 1, 11, 21, 14, 33, 913, DateTimeKind.Local).AddTicks(2698),
                            Data_Nasc = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 4,
                            Nome = "Luiza",
                            Sobrenome = "Maria",
                            Telefone = "6565659"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            Data_Inicio = new DateTime(2022, 1, 11, 21, 14, 33, 913, DateTimeKind.Local).AddTicks(2708),
                            Data_Nasc = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 5,
                            Nome = "Lucas",
                            Sobrenome = "Machado",
                            Telefone = "565685415"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            Data_Inicio = new DateTime(2022, 1, 11, 21, 14, 33, 913, DateTimeKind.Local).AddTicks(2787),
                            Data_Nasc = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 6,
                            Nome = "Pedro",
                            Sobrenome = "Alvares",
                            Telefone = "456454545"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            Data_Inicio = new DateTime(2022, 1, 11, 21, 14, 33, 913, DateTimeKind.Local).AddTicks(2798),
                            Data_Nasc = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 7,
                            Nome = "Paulo",
                            Sobrenome = "José",
                            Telefone = "9874512"
                        });
                });

            modelBuilder.Entity("School.API.Models.AlunoCurso", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CursoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Data_Fim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data_Inicio")
                        .HasColumnType("TEXT");

                    b.HasKey("AlunoId", "CursoId");

                    b.HasIndex("CursoId");

                    b.ToTable("AlunosCursos");
                });

            modelBuilder.Entity("School.API.Models.AlunoDisciplina", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Data_Fim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data_Inicio")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Nota")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlunoId", "DisciplinaId");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("AlunosDisciplinas");

                    b.HasData(
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 2,
                            Data_Inicio = new DateTime(2022, 1, 11, 21, 14, 33, 913, DateTimeKind.Local).AddTicks(4821)
                        },
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 4,
                            Data_Inicio = new DateTime(2022, 1, 11, 21, 14, 33, 913, DateTimeKind.Local).AddTicks(5732)
                        },
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 5,
                            Data_Inicio = new DateTime(2022, 1, 11, 21, 14, 33, 913, DateTimeKind.Local).AddTicks(5762)
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 1,
                            Data_Inicio = new DateTime(2022, 1, 11, 21, 14, 33, 913, DateTimeKind.Local).AddTicks(5764)
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 2,
                            Data_Inicio = new DateTime(2022, 1, 11, 21, 14, 33, 913, DateTimeKind.Local).AddTicks(5766)
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 5,
                            Data_Inicio = new DateTime(2022, 1, 11, 21, 14, 33, 913, DateTimeKind.Local).AddTicks(5772)
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 1,
                            Data_Inicio = new DateTime(2022, 1, 11, 21, 14, 33, 913, DateTimeKind.Local).AddTicks(5774)
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 2,
                            Data_Inicio = new DateTime(2022, 1, 11, 21, 14, 33, 913, DateTimeKind.Local).AddTicks(5777)
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 3,
                            Data_Inicio = new DateTime(2022, 1, 11, 21, 14, 33, 913, DateTimeKind.Local).AddTicks(5779)
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 1,
                            Data_Inicio = new DateTime(2022, 1, 11, 21, 14, 33, 913, DateTimeKind.Local).AddTicks(5783)
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 4,
                            Data_Inicio = new DateTime(2022, 1, 11, 21, 14, 33, 913, DateTimeKind.Local).AddTicks(5785)
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 5,
                            Data_Inicio = new DateTime(2022, 1, 11, 21, 14, 33, 913, DateTimeKind.Local).AddTicks(5787)
                        },
                        new
                        {
                            AlunoId = 5,
                            DisciplinaId = 4,
                            Data_Inicio = new DateTime(2022, 1, 11, 21, 14, 33, 913, DateTimeKind.Local).AddTicks(5789)
                        },
                        new
                        {
                            AlunoId = 5,
                            DisciplinaId = 5,
                            Data_Inicio = new DateTime(2022, 1, 11, 21, 14, 33, 913, DateTimeKind.Local).AddTicks(5791)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 1,
                            Data_Inicio = new DateTime(2022, 1, 11, 21, 14, 33, 913, DateTimeKind.Local).AddTicks(5793)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 2,
                            Data_Inicio = new DateTime(2022, 1, 11, 21, 14, 33, 913, DateTimeKind.Local).AddTicks(5795)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 3,
                            Data_Inicio = new DateTime(2022, 1, 11, 21, 14, 33, 913, DateTimeKind.Local).AddTicks(5798)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 4,
                            Data_Inicio = new DateTime(2022, 1, 11, 21, 14, 33, 913, DateTimeKind.Local).AddTicks(5802)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 1,
                            Data_Inicio = new DateTime(2022, 1, 11, 21, 14, 33, 913, DateTimeKind.Local).AddTicks(5804)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 2,
                            Data_Inicio = new DateTime(2022, 1, 11, 21, 14, 33, 913, DateTimeKind.Local).AddTicks(5806)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 3,
                            Data_Inicio = new DateTime(2022, 1, 11, 21, 14, 33, 913, DateTimeKind.Local).AddTicks(5808)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 4,
                            Data_Inicio = new DateTime(2022, 1, 11, 21, 14, 33, 913, DateTimeKind.Local).AddTicks(5810)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 5,
                            Data_Inicio = new DateTime(2022, 1, 11, 21, 14, 33, 913, DateTimeKind.Local).AddTicks(5812)
                        });
                });

            modelBuilder.Entity("School.API.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cursos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Tecnologia da Informação"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Sistemas de Informação"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Ciência da Computação"
                        });
                });

            modelBuilder.Entity("School.API.Models.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CursoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrerequisitoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("PrerequisitoId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Disciplinas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CargaHoraria = 0,
                            CursoId = 1,
                            Nome = "Matemática",
                            ProfessorId = 1
                        },
                        new
                        {
                            Id = 2,
                            CargaHoraria = 0,
                            CursoId = 3,
                            Nome = "Matemática",
                            ProfessorId = 1
                        },
                        new
                        {
                            Id = 3,
                            CargaHoraria = 0,
                            CursoId = 3,
                            Nome = "Física",
                            ProfessorId = 2
                        },
                        new
                        {
                            Id = 4,
                            CargaHoraria = 0,
                            CursoId = 1,
                            Nome = "Português",
                            ProfessorId = 3
                        },
                        new
                        {
                            Id = 5,
                            CargaHoraria = 0,
                            CursoId = 1,
                            Nome = "Inglês",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 6,
                            CargaHoraria = 0,
                            CursoId = 2,
                            Nome = "Inglês",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 7,
                            CargaHoraria = 0,
                            CursoId = 3,
                            Nome = "Inglês",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 8,
                            CargaHoraria = 0,
                            CursoId = 1,
                            Nome = "Programação",
                            ProfessorId = 5
                        },
                        new
                        {
                            Id = 9,
                            CargaHoraria = 0,
                            CursoId = 2,
                            Nome = "Programação",
                            ProfessorId = 5
                        },
                        new
                        {
                            Id = 10,
                            CargaHoraria = 0,
                            CursoId = 3,
                            Nome = "Programação",
                            ProfessorId = 5
                        });
                });

            modelBuilder.Entity("School.API.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Data_Fim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data_Inicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data_Nasc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("Registro")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Professores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Data_Inicio = new DateTime(2022, 1, 11, 21, 14, 33, 905, DateTimeKind.Local).AddTicks(1543),
                            Data_Nasc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Lauro",
                            Registro = 1,
                            Sobrenome = "Oliveira",
                            Telefone = "15"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Data_Inicio = new DateTime(2022, 1, 11, 21, 14, 33, 906, DateTimeKind.Local).AddTicks(3112),
                            Data_Nasc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Roberto",
                            Registro = 2,
                            Sobrenome = "Soares",
                            Telefone = "15"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Data_Inicio = new DateTime(2022, 1, 11, 21, 14, 33, 906, DateTimeKind.Local).AddTicks(3162),
                            Data_Nasc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Ronaldo",
                            Registro = 3,
                            Sobrenome = "Marconi",
                            Telefone = "15"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Data_Inicio = new DateTime(2022, 1, 11, 21, 14, 33, 906, DateTimeKind.Local).AddTicks(3164),
                            Data_Nasc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Rodrigo",
                            Registro = 4,
                            Sobrenome = "Carvalho",
                            Telefone = "15"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            Data_Inicio = new DateTime(2022, 1, 11, 21, 14, 33, 906, DateTimeKind.Local).AddTicks(3166),
                            Data_Nasc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Alexandre",
                            Registro = 5,
                            Sobrenome = "Montanha",
                            Telefone = "15"
                        });
                });

            modelBuilder.Entity("School.API.Models.AlunoCurso", b =>
                {
                    b.HasOne("School.API.Models.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School.API.Models.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("School.API.Models.AlunoDisciplina", b =>
                {
                    b.HasOne("School.API.Models.Aluno", "Aluno")
                        .WithMany("AlunosDisciplinas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School.API.Models.Disciplina", "Disciplina")
                        .WithMany("AlunosDisciplinas")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("School.API.Models.Disciplina", b =>
                {
                    b.HasOne("School.API.Models.Curso", "Curso")
                        .WithMany("Disciplinas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School.API.Models.Disciplina", "Prerequisito")
                        .WithMany()
                        .HasForeignKey("PrerequisitoId");

                    b.HasOne("School.API.Models.Professor", "Professor")
                        .WithMany("Disciplina")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
