// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using School.API.Data;

namespace School.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("School.API.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("Data_Fim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Data_Inicio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Data_Nasc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Matricula")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Data_Inicio = new DateTime(2022, 1, 21, 21, 43, 46, 988, DateTimeKind.Local).AddTicks(8378),
                            Data_Nasc = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 1,
                            Nome = "Marta",
                            Sobrenome = "Kent",
                            Telefone = "33225555"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Data_Inicio = new DateTime(2022, 1, 21, 21, 43, 46, 989, DateTimeKind.Local).AddTicks(914),
                            Data_Nasc = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 2,
                            Nome = "Paula",
                            Sobrenome = "Isabela",
                            Telefone = "3354288"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Data_Inicio = new DateTime(2022, 1, 21, 21, 43, 46, 989, DateTimeKind.Local).AddTicks(1723),
                            Data_Nasc = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 3,
                            Nome = "Laura",
                            Sobrenome = "Antonia",
                            Telefone = "55668899"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Data_Inicio = new DateTime(2022, 1, 21, 21, 43, 46, 989, DateTimeKind.Local).AddTicks(1739),
                            Data_Nasc = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 4,
                            Nome = "Luiza",
                            Sobrenome = "Maria",
                            Telefone = "6565659"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            Data_Inicio = new DateTime(2022, 1, 21, 21, 43, 46, 989, DateTimeKind.Local).AddTicks(1746),
                            Data_Nasc = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 5,
                            Nome = "Lucas",
                            Sobrenome = "Machado",
                            Telefone = "565685415"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            Data_Inicio = new DateTime(2022, 1, 21, 21, 43, 46, 989, DateTimeKind.Local).AddTicks(1762),
                            Data_Nasc = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 6,
                            Nome = "Pedro",
                            Sobrenome = "Alvares",
                            Telefone = "456454545"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            Data_Inicio = new DateTime(2022, 1, 21, 21, 43, 46, 989, DateTimeKind.Local).AddTicks(1769),
                            Data_Nasc = new DateTime(2005, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 7,
                            Nome = "Paulo",
                            Sobrenome = "José",
                            Telefone = "9874512"
                        });
                });

            modelBuilder.Entity("School.API.Models.AlunoCurso", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Data_Fim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Data_Inicio")
                        .HasColumnType("datetime(6)");

                    b.HasKey("AlunoId", "CursoId");

                    b.HasIndex("CursoId");

                    b.ToTable("AlunosCursos");
                });

            modelBuilder.Entity("School.API.Models.AlunoDisciplina", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Data_Fim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Data_Inicio")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Nota")
                        .HasColumnType("int");

                    b.HasKey("AlunoId", "DisciplinaId");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("AlunosDisciplinas");

                    b.HasData(
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 2,
                            Data_Inicio = new DateTime(2022, 1, 21, 21, 43, 46, 989, DateTimeKind.Local).AddTicks(4648)
                        },
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 4,
                            Data_Inicio = new DateTime(2022, 1, 21, 21, 43, 46, 989, DateTimeKind.Local).AddTicks(5590)
                        },
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 5,
                            Data_Inicio = new DateTime(2022, 1, 21, 21, 43, 46, 989, DateTimeKind.Local).AddTicks(5620)
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 1,
                            Data_Inicio = new DateTime(2022, 1, 21, 21, 43, 46, 989, DateTimeKind.Local).AddTicks(5623)
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 2,
                            Data_Inicio = new DateTime(2022, 1, 21, 21, 43, 46, 989, DateTimeKind.Local).AddTicks(5625)
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 5,
                            Data_Inicio = new DateTime(2022, 1, 21, 21, 43, 46, 989, DateTimeKind.Local).AddTicks(5631)
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 1,
                            Data_Inicio = new DateTime(2022, 1, 21, 21, 43, 46, 989, DateTimeKind.Local).AddTicks(5633)
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 2,
                            Data_Inicio = new DateTime(2022, 1, 21, 21, 43, 46, 989, DateTimeKind.Local).AddTicks(5636)
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 3,
                            Data_Inicio = new DateTime(2022, 1, 21, 21, 43, 46, 989, DateTimeKind.Local).AddTicks(5638)
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 1,
                            Data_Inicio = new DateTime(2022, 1, 21, 21, 43, 46, 989, DateTimeKind.Local).AddTicks(5642)
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 4,
                            Data_Inicio = new DateTime(2022, 1, 21, 21, 43, 46, 989, DateTimeKind.Local).AddTicks(5645)
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 5,
                            Data_Inicio = new DateTime(2022, 1, 21, 21, 43, 46, 989, DateTimeKind.Local).AddTicks(5647)
                        },
                        new
                        {
                            AlunoId = 5,
                            DisciplinaId = 4,
                            Data_Inicio = new DateTime(2022, 1, 21, 21, 43, 46, 989, DateTimeKind.Local).AddTicks(5649)
                        },
                        new
                        {
                            AlunoId = 5,
                            DisciplinaId = 5,
                            Data_Inicio = new DateTime(2022, 1, 21, 21, 43, 46, 989, DateTimeKind.Local).AddTicks(5651)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 1,
                            Data_Inicio = new DateTime(2022, 1, 21, 21, 43, 46, 989, DateTimeKind.Local).AddTicks(5653)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 2,
                            Data_Inicio = new DateTime(2022, 1, 21, 21, 43, 46, 989, DateTimeKind.Local).AddTicks(5656)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 3,
                            Data_Inicio = new DateTime(2022, 1, 21, 21, 43, 46, 989, DateTimeKind.Local).AddTicks(5658)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 4,
                            Data_Inicio = new DateTime(2022, 1, 21, 21, 43, 46, 989, DateTimeKind.Local).AddTicks(5662)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 1,
                            Data_Inicio = new DateTime(2022, 1, 21, 21, 43, 46, 989, DateTimeKind.Local).AddTicks(5664)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 2,
                            Data_Inicio = new DateTime(2022, 1, 21, 21, 43, 46, 989, DateTimeKind.Local).AddTicks(5666)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 3,
                            Data_Inicio = new DateTime(2022, 1, 21, 21, 43, 46, 989, DateTimeKind.Local).AddTicks(5669)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 4,
                            Data_Inicio = new DateTime(2022, 1, 21, 21, 43, 46, 989, DateTimeKind.Local).AddTicks(5671)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 5,
                            Data_Inicio = new DateTime(2022, 1, 21, 21, 43, 46, 989, DateTimeKind.Local).AddTicks(5673)
                        });
                });

            modelBuilder.Entity("School.API.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Cursos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Tecnologia da Informação"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Sistemas de Informação"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Ciência da Computação"
                        });
                });

            modelBuilder.Entity("School.API.Models.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("int");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("PrerequisitoId")
                        .HasColumnType("int");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("PrerequisitoId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Disciplinas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CargaHoraria = 0,
                            CursoId = 1,
                            Nome = "Matemática",
                            ProfessorId = 1
                        },
                        new
                        {
                            Id = 2,
                            CargaHoraria = 0,
                            CursoId = 3,
                            Nome = "Matemática",
                            ProfessorId = 1
                        },
                        new
                        {
                            Id = 3,
                            CargaHoraria = 0,
                            CursoId = 3,
                            Nome = "Física",
                            ProfessorId = 2
                        },
                        new
                        {
                            Id = 4,
                            CargaHoraria = 0,
                            CursoId = 1,
                            Nome = "Português",
                            ProfessorId = 3
                        },
                        new
                        {
                            Id = 5,
                            CargaHoraria = 0,
                            CursoId = 1,
                            Nome = "Inglês",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 6,
                            CargaHoraria = 0,
                            CursoId = 2,
                            Nome = "Inglês",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 7,
                            CargaHoraria = 0,
                            CursoId = 3,
                            Nome = "Inglês",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 8,
                            CargaHoraria = 0,
                            CursoId = 1,
                            Nome = "Programação",
                            ProfessorId = 5
                        },
                        new
                        {
                            Id = 9,
                            CargaHoraria = 0,
                            CursoId = 2,
                            Nome = "Programação",
                            ProfessorId = 5
                        },
                        new
                        {
                            Id = 10,
                            CargaHoraria = 0,
                            CursoId = 3,
                            Nome = "Programação",
                            ProfessorId = 5
                        });
                });

            modelBuilder.Entity("School.API.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("Data_Fim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Data_Inicio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Data_Nasc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Registro")
                        .HasColumnType("int");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Professores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Data_Inicio = new DateTime(2022, 1, 21, 21, 43, 46, 985, DateTimeKind.Local).AddTicks(5905),
                            Data_Nasc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Lauro",
                            Registro = 1,
                            Sobrenome = "Oliveira",
                            Telefone = "15"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Data_Inicio = new DateTime(2022, 1, 21, 21, 43, 46, 986, DateTimeKind.Local).AddTicks(3597),
                            Data_Nasc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Roberto",
                            Registro = 2,
                            Sobrenome = "Soares",
                            Telefone = "15"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Data_Inicio = new DateTime(2022, 1, 21, 21, 43, 46, 986, DateTimeKind.Local).AddTicks(3662),
                            Data_Nasc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Ronaldo",
                            Registro = 3,
                            Sobrenome = "Marconi",
                            Telefone = "15"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Data_Inicio = new DateTime(2022, 1, 21, 21, 43, 46, 986, DateTimeKind.Local).AddTicks(3665),
                            Data_Nasc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Rodrigo",
                            Registro = 4,
                            Sobrenome = "Carvalho",
                            Telefone = "15"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            Data_Inicio = new DateTime(2022, 1, 21, 21, 43, 46, 986, DateTimeKind.Local).AddTicks(3667),
                            Data_Nasc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Alexandre",
                            Registro = 5,
                            Sobrenome = "Montanha",
                            Telefone = "15"
                        });
                });

            modelBuilder.Entity("School.API.Models.AlunoCurso", b =>
                {
                    b.HasOne("School.API.Models.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School.API.Models.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("School.API.Models.AlunoDisciplina", b =>
                {
                    b.HasOne("School.API.Models.Aluno", "Aluno")
                        .WithMany("AlunosDisciplinas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School.API.Models.Disciplina", "Disciplina")
                        .WithMany("AlunosDisciplinas")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("School.API.Models.Disciplina", b =>
                {
                    b.HasOne("School.API.Models.Curso", "Curso")
                        .WithMany("Disciplinas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("School.API.Models.Disciplina", "Prerequisito")
                        .WithMany()
                        .HasForeignKey("PrerequisitoId");

                    b.HasOne("School.API.Models.Professor", "Professor")
                        .WithMany("Disciplina")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
